language: generic
sudo: required
services:
    - docker
    
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - docker build -t gileyni/multi-client-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true gileyni/multi-client-test npm run test
    
after_success:
    - docker build -t gileyni/multi-client ./client
    - docker build -t gileyni/multi-nginx ./nginx
    - docker build -t gileyni/multi-server ./server
    - docker build -t gileyni/multi-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push gileyni/multi-client
    - docker push gileyni/multi-nginx
    - docker push gileyni/multi-server
    - docker push gileyni/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-eu-west-2-766919854470"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY